from boyGenerous import *
from boyMiser import *
from boyGeek import *
from giftEssential import *
from giftLuxury import *
from giftUtility import *
from girlNormal import *
from girlChoosy import *
from girlDesperate import *
import csv

arrBoys = []
arrGirls = []
Gifts = []

class read:
    def __init__(self):
        pass

    '''lass for reading csv files generated by generator.py'''
    def readcsvfile(self, charType):

        if charType == 'b':
            file = csv.DictReader(open("boys.csv"))
            for tmp in file:
                if (tmp['bType'] == 'miser'):
                    temp_boy = boyMiser(tmp)
                elif (tmp['bType'] == 'generous'):
                    temp_boy = boyGenerous(tmp)
                else:
                    temp_boy = boyGeek(tmp)
                arrBoys.append(temp_boy)

            return arrBoys

        elif charType == 'g':
            file = csv.DictReader(open("girls.csv"))
            for tmp in file:
                if (tmp['gType'] == 'choosy'):
                    temp_girl = girlChoosy(tmp)
                if (tmp['gType'] == 'normal'):
                    temp_girl = girlNormal(tmp)
                if (tmp['gType'] == 'desperate'):
                    temp_girl = girlDesperate(tmp)
                arrGirls.append(temp_girl)

        else:
            file = csv.DictReader(open("gifts.csv"))
            for tmp in file:
                if (tmp['giftType'] == 'Essential'):
                    gift = giftEssential(tmp)
                elif (tmp['giftType'] == 'Luxury'):
                    gift = giftLuxury(tmp)
                else:
                    gift = giftUtility(tmp)
                Gifts.append(gift)

